runtime: python27
api_version: 1
threadsafe: yes

handlers:
  - url: /
    static_files: dist/pwa/index.html
    upload: dist/pwa/index.html
    secure: always
  - url: /
    static_dir: dist/pwa
    secure: always

skip_files:
  - e2e/
  - node_modules/
  - src/
  - ^(.*/)?\..*$
  - ^(\b(?!dist\b)\w+)\.json$
  - ^(.*/)?.*\.md$
  - ^(.*/)?.*\.yaml$
  - ^LICENSE
  - dist/spa/
  - .quasar
